# Generated by Django 4.0 on 2021-12-27 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weeb_shit', '0003_list_of_anime_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='auto_complete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_anime', models.CharField(blank=True, default='some string', max_length=1000)),
            ],
        ),
        migrations.RemoveField(
            model_name='list_of_anime',
            name='type',
        ),
    ]
