# Generated by Django 4.0 on 2021-12-27 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weeb_shit', '0004_auto_complete_remove_list_of_anime_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='auto_complete',
            name='slug',
            field=models.SlugField(default='test'),
        ),
        migrations.AddField(
            model_name='list_of_anime',
            name='genre',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='list_of_anime',
            name='mode',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='list_of_anime',
            name='score',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
