# Generated by Django 4.0 on 2021-12-27 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weeb_shit', '0005_auto_complete_slug_list_of_anime_genre_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='anime_database',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numofep', models.CharField(blank=True, max_length=4, null=True)),
                ('releaseyear', models.CharField(blank=True, max_length=4, null=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('picture', models.CharField(blank=True, max_length=1000, null=True)),
                ('MAL_ID', models.CharField(blank=True, max_length=100, null=True)),
                ('synopsis', models.CharField(blank=True, max_length=100000, null=True)),
                ('score', models.CharField(blank=True, max_length=5, null=True)),
                ('genre', models.CharField(blank=True, max_length=100, null=True)),
                ('mode', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='list_of_anime',
            name='genre',
        ),
        migrations.RemoveField(
            model_name='list_of_anime',
            name='mode',
        ),
    ]
