# Generated by Django 4.0 on 2022-02-04 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('weeb_shit', '0007_alter_anime_database_numofep_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='twostars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('animes', models.ManyToManyField(to='weeb_shit.anime_database')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weeb_shit.profile')),
            ],
        ),
        migrations.CreateModel(
            name='threestars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('animes', models.ManyToManyField(to='weeb_shit.anime_database')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weeb_shit.profile')),
            ],
        ),
        migrations.CreateModel(
            name='onestars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('animes', models.ManyToManyField(to='weeb_shit.anime_database')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weeb_shit.profile')),
            ],
        ),
        migrations.CreateModel(
            name='fourstars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('animes', models.ManyToManyField(to='weeb_shit.anime_database')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weeb_shit.profile')),
            ],
        ),
        migrations.CreateModel(
            name='fivestars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('animes', models.ManyToManyField(to='weeb_shit.anime_database')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weeb_shit.profile')),
            ],
        ),
    ]
