# Generated by Django 4.0 on 2022-02-04 13:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('weeb_shit', '0008_twostars_threestars_onestars_fourstars_fivestars'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fivestars',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='weeb_shit.profile'),
        ),
        migrations.AlterField(
            model_name='fourstars',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='weeb_shit.profile'),
        ),
        migrations.AlterField(
            model_name='onestars',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='weeb_shit.profile'),
        ),
        migrations.AlterField(
            model_name='threestars',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='weeb_shit.profile'),
        ),
        migrations.AlterField(
            model_name='twostars',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='weeb_shit.profile'),
        ),
    ]
