# Generated by Django 4.0 on 2022-02-25 12:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('weeb_shit', '0012_watchedgenre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watchedgenre',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weeb_shit.profile'),
        ),
    ]
