# Generated by Django 4.0 on 2022-02-25 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weeb_shit', '0013_alter_watchedgenre_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watchedgenre',
            name='count',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
